deployment:
  name: "webserver"
  replicas: "3 "
  strategy:
    rollingUpdate:
      maxSurge: "1"
      maxUnavailable: "1"
  container:
    name: "webserver"
    image: "fatihkoc/app:latest"
    imagePullPolicy: "Always"
    port: "8080"
    protocol: "TCP"
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"
      limits:
        cpu: "110m"
        memory: "110Mi"
    env:
      APP_NAME: "webserver"
    livenessProbe:
      path: "/health"
      port: "8080"
      initialDelaySeconds: "30"
      timeoutSeconds: "5"
    readinessProbe:
      path: "/health"
      port: "8080"
      initialDelaySeconds: "30"
      timeoutSeconds: "5"

service:
  name: "webserver"
  selector:
    name: "webserver"
  ports:
    protocol: "TCP"
    port: "8080"
    targetPort: "8080"
    type: "NodePort"
    nodePort: "30000"

configmap:
  key: USER
  value: "Fatih"